/* ============================================================
   NEZO X ID — Data layer
   Account listings + FAQ database
   In a production deployment these would be served from a CMS
   or database; here they are bundled as static JSON for speed.
   ============================================================ */

const ACCOUNTS = [
  {
    id: 101,
    uid: "FF-118402231",
    name: "Heroic Nova — Bundle King",
    level: 78,
    rank: "Heroic",
    price: 1850000,
    oldPrice: 2300000,
    status: "available",
    featured: true,
    popular: true,
    dateAdded: "2026-06-09",
    region: "Global / SEA bind",
    skins: ["Cyber Wolf AK", "Phantom Bike", "Galaxy Parachute", "Inferno Outfit"],
    evoGuns: ["Evo M1887 - Lv.6", "Evo MP40 - Lv.5"],
    desc: "Stacked Heroic-rank account with a curated bundle collection, dual maxed evo guns and a fully customized loadout. Great for collectors who want instant clout.",
    badges: ["Bundle Heavy", "Rare Pet"],
  },
  {
    id: 102,
    uid: "FF-220981772",
    name: "Grandmaster Vault",
    level: 81,
    rank: "Grandmaster",
    price: 4200000,
    oldPrice: 5100000,
    status: "available",
    featured: true,
    popular: true,
    dateAdded: "2026-06-11",
    region: "Global",
    skins: ["Dragon Throne Set", "Golden M4A1", "Mecha Bear Pet Skin", "Sakura Parachute"],
    evoGuns: ["Evo M4A1 - Lv.6", "Evo AWM - Lv.6", "Evo Groza - Lv.5"],
    desc: "Top-tier ranked account sitting in Grandmaster with three fully evolved weapons, a Dragon Throne bundle set and an account history clean of bans.",
    badges: ["Grandmaster", "3x Evo Lv.6"],
  },
  {
    id: 103,
    uid: "FF-339012456",
    name: "Starter Surge",
    level: 34,
    rank: "Platinum",
    price: 320000,
    oldPrice: null,
    status: "available",
    featured: false,
    popular: true,
    dateAdded: "2026-06-10",
    region: "SEA",
    skins: ["Aurora Backpack", "Neon Runner Outfit"],
    evoGuns: ["Evo Scar - Lv.3"],
    desc: "Budget-friendly account ideal for new players who want a head start with a clean inventory, decent skins and a partially evolved weapon.",
    badges: ["Beginner Friendly"],
  },
  {
    id: 104,
    uid: "FF-447723019",
    name: "Elite Reaper",
    level: 65,
    rank: "Diamond",
    price: 980000,
    oldPrice: 1150000,
    status: "available",
    featured: false,
    popular: false,
    dateAdded: "2026-06-08",
    region: "Global",
    skins: ["Reaper Outfit Set", "Shadow Wolf Gloo Wall", "Crimson Parachute"],
    evoGuns: ["Evo Ump - Lv.4", "Evo Xm8 - Lv.4"],
    desc: "Diamond-tier account with a dark-themed bundle collection and twin evo weapons. Comes with several limited-edition emotes from past events.",
    badges: ["Limited Emotes"],
  },
  {
    id: 105,
    uid: "FF-554981203",
    name: "Phoenix Ascend",
    level: 72,
    rank: "Heroic",
    price: 1620000,
    oldPrice: 1900000,
    status: "available",
    featured: true,
    popular: false,
    dateAdded: "2026-06-12",
    region: "Global",
    skins: ["Phoenix Wing Backpack", "Inferno Bike", "Solar Flame Outfit"],
    evoGuns: ["Evo M1887 - Lv.5", "Evo AK47 - Lv.5"],
    desc: "Heroic rank account with a fire-themed cosmetic set and two near-maxed evo guns. Pet collection includes three legendary pets at max skill level.",
    badges: ["3 Legendary Pets"],
  },
  {
    id: 106,
    uid: "FF-661120347",
    name: "Frostbyte",
    level: 58,
    rank: "Diamond",
    price: 740000,
    oldPrice: null,
    status: "pending",
    featured: false,
    popular: false,
    dateAdded: "2026-06-05",
    region: "SEA",
    skins: ["Glacier Outfit", "Ice Queen Parachute"],
    evoGuns: ["Evo M4A1 - Lv.3"],
    desc: "Cool-toned ice aesthetic account currently reserved for a buyer in verification. Will return to available if the order isn't completed within 24 hours.",
    badges: ["Reserved"],
  },
  {
    id: 107,
    uid: "FF-772209814",
    name: "Obsidian Master",
    level: 88,
    rank: "Grandmaster",
    price: 5600000,
    oldPrice: 6500000,
    status: "available",
    featured: true,
    popular: true,
    dateAdded: "2026-06-07",
    region: "Global",
    skins: ["Obsidian Knight Set", "Void Walker Pet Skin", "Eclipse Parachute", "Black Hole Gloo Wall"],
    evoGuns: ["Evo AWM - Lv.6", "Evo M4A1 - Lv.6", "Evo Groza - Lv.6", "Evo Mp40 - Lv.6"],
    desc: "Our flagship listing — a max-level Grandmaster account with four fully evolved level 6 weapons, a complete dark-themed bundle vault and verified clean history.",
    badges: ["4x Evo Lv.6", "Flagship"],
  },
  {
    id: 108,
    uid: "FF-883401129",
    name: "Sunrise Recruit",
    level: 22,
    rank: "Gold",
    price: 180000,
    oldPrice: null,
    status: "available",
    featured: false,
    popular: false,
    dateAdded: "2026-06-03",
    region: "Global",
    skins: ["Sunrise Outfit", "Basic Backpack Skin"],
    evoGuns: [],
    desc: "Entry-level account with a fresh inventory, a couple of starter skins and no evo guns yet — perfect base for building your own collection.",
    badges: ["Fresh Account"],
  },
  {
    id: 109,
    uid: "FF-991203488",
    name: "Velocity Striker",
    level: 69,
    rank: "Diamond",
    price: 1120000,
    oldPrice: 1300000,
    status: "available",
    featured: false,
    popular: true,
    dateAdded: "2026-06-11",
    region: "SEA",
    skins: ["Velocity Racer Suit", "Turbo Bike Skin", "Speed Demon Parachute"],
    evoGuns: ["Evo Scar - Lv.5", "Evo M1887 - Lv.4"],
    desc: "Built for speed-run rushers, this Diamond account comes with a full racing-themed bundle set and two well-evolved shotguns and rifles.",
    badges: ["Rush Build"],
  },
  {
    id: 110,
    uid: "FF-102938475",
    name: "Mythic Samurai",
    level: 91,
    rank: "Grandmaster",
    price: 6800000,
    oldPrice: 7900000,
    status: "sold",
    featured: false,
    popular: false,
    dateAdded: "2026-05-29",
    region: "Global",
    skins: ["Mythic Samurai Set", "Katana Bundle", "Dragon Crest Parachute"],
    evoGuns: ["Evo AWM - Lv.6", "Evo Groza - Lv.6"],
    desc: "This premium Samurai-themed Grandmaster account has been successfully delivered to its new owner. New similar listings are added regularly — message us to get notified.",
    badges: ["Sold Out"],
  },
  {
    id: 111,
    uid: "FF-213847566",
    name: "Neon Drifter",
    level: 47,
    rank: "Platinum",
    price: 520000,
    oldPrice: 600000,
    status: "available",
    featured: false,
    popular: false,
    dateAdded: "2026-06-04",
    region: "Global",
    skins: ["Neon Drift Outfit", "Cyber Visor", "Holo Parachute"],
    evoGuns: ["Evo Ump - Lv.3"],
    desc: "Cyberpunk-styled Platinum account with a vibrant neon collection that stands out in the lobby. Includes a partially evolved SMG.",
    badges: ["Cyberpunk Theme"],
  },
  {
    id: 112,
    uid: "FF-324958607",
    name: "Crimson Vanguard",
    level: 75,
    rank: "Heroic",
    price: 1450000,
    oldPrice: null,
    status: "available",
    featured: false,
    popular: false,
    dateAdded: "2026-06-06",
    region: "Global",
    skins: ["Crimson Vanguard Armor", "Blood Moon Bike", "Scarlet Parachute"],
    evoGuns: ["Evo M4A1 - Lv.5", "Evo Mp40 - Lv.4"],
    desc: "Heroic-rank account with a striking red armor bundle set and a balanced loadout of two evo weapons — well rounded for ranked grinding.",
    badges: ["Ranked Ready"],
  },
  {
    id: 113,
    uid: "FF-435069718",
    name: "Lunar Phantom",
    level: 63,
    rank: "Diamond",
    price: 890000,
    oldPrice: 1020000,
    status: "available",
    featured: false,
    popular: false,
    dateAdded: "2026-06-02",
    region: "SEA",
    skins: ["Lunar Phantom Set", "Moonlight Pet Skin", "Starlight Gloo Wall"],
    evoGuns: ["Evo Scar - Lv.4"],
    desc: "Elegant moon-themed Diamond account with a softly glowing bundle set and a single evolved assault rifle. Includes a rare moonlight emote.",
    badges: ["Rare Emote"],
  },
  {
    id: 114,
    uid: "FF-546170829",
    name: "Apex Titan",
    level: 84,
    rank: "Grandmaster",
    price: 3950000,
    oldPrice: 4600000,
    status: "available",
    featured: true,
    popular: false,
    dateAdded: "2026-06-12",
    region: "Global",
    skins: ["Apex Titan Mech Suit", "Titanium Bike Skin", "Storm Parachute", "Iron Will Gloo Wall"],
    evoGuns: ["Evo M4A1 - Lv.6", "Evo AWM - Lv.5"],
    desc: "Mech-armor themed Grandmaster account with one fully maxed evo gun and one near-maxed, plus a complete Titan-series cosmetic vault.",
    badges: ["Mech Theme"],
  },
];

const FAQ_DATA = [
  // Payment
  { category: "Payment", q: "Which payment methods are accepted?", a: "We accept bank transfers, e-wallets (DANA, OVO, GoPay, ShopeePay), and most regional mobile payment services. After choosing an account on WhatsApp, our team will confirm the available options for your region." },
  { category: "Payment", q: "How long does payment verification take?", a: "Most payments are verified within 5–30 minutes during business hours. For bank transfers outside business hours, verification may take up to a few hours, but our team will keep you updated throughout." },
  { category: "Payment", q: "Is it safe to pay before receiving the account?", a: "Yes. We use an escrow-style process where payment confirmation and account handover happen in the same chat session, with our team verifying both sides before finalizing the trade." },
  { category: "Payment", q: "Do you offer installment or partial payment options?", a: "For higher-value Grandmaster accounts, we can arrange a split payment across two transactions for trusted repeat customers — just ask our team when chatting on WhatsApp." },
  { category: "Payment", q: "Are there any hidden fees?", a: "No. The price listed on each account card is the full price you pay — there are no hidden service charges or surprise add-ons." },

  // Account delivery
  { category: "Account", q: "How will I receive my account?", a: "Once payment is verified, our team sends the login credentials, linked email/phone access details, and a short handover guide directly through WhatsApp, usually within 10–20 minutes." },
  { category: "Account", q: "What information is included with the account?", a: "Each delivery includes the account login (email or phone + password), any linked social login details if applicable, a full inventory summary, and basic security tips for changing credentials safely." },
  { category: "Account", q: "Can I change the linked email and phone number after purchase?", a: "Yes, and we strongly recommend it. We provide step-by-step instructions for updating the linked email, phone number, and password immediately after delivery to fully secure your new account." },
  { category: "Account", q: "Will the account stats match what's shown on the listing?", a: "Yes. Every listing reflects the account's real-time level, rank, skins, and evo guns at the time of posting. If anything changes before delivery, we notify you before finalizing the order." },
  { category: "Account", q: "Do accounts come with linked Facebook or VK logins?", a: "Some accounts include a linked social login for convenience, which is noted in the account description. If a listing doesn't mention it, the account uses a guest or phone-based login." },

  // Refunds
  { category: "Refunds", q: "What is the refund policy?", a: "If an account is found to differ significantly from its listing description (level, rank, skins, or evo guns), you're eligible for a full refund or a replacement account of equal value within 24 hours of delivery." },
  { category: "Refunds", q: "Can I get a refund after account delivery?", a: "Refunds are available within 24 hours of delivery only if the account does not match the listed specifications, becomes inaccessible due to our error, or was not as described. Buyer's remorse alone does not qualify for a refund — see our Terms & Conditions for full details." },
  { category: "Refunds", q: "How long does a refund take?", a: "Approved refunds are processed within 1–3 business days back to your original payment method, and our team will message you a confirmation once it's complete." },
  { category: "Refunds", q: "What happens if the account gets banned shortly after purchase?", a: "If the account is suspended due to a pre-existing issue from before the sale, we offer a replacement account or refund. Bans resulting from the buyer's own actions after handover are not covered." },

  // Security & trust
  { category: "Security", q: "Are these accounts legally obtained?", a: "All accounts listed are sourced through legitimate player transfers and verified before listing. We do not list accounts obtained through hacking, phishing, or unauthorized access." },
  { category: "Security", q: "Will my purchase information be shared with anyone?", a: "No. Your contact details and transaction information are kept private and used only to process your order, in line with our Privacy Policy." },
  { category: "Security", q: "Is there a risk the seller takes back the account later?", a: "Once an account is sold and credentials are changed by you, the previous owner loses access entirely. We require sellers to confirm full handover before listings go live." },
  { category: "Security", q: "How do you verify accounts before listing them?", a: "Our team manually logs into each account, checks the rank, level, inventory, evo gun levels, and ban history, and takes verification screenshots before publishing the listing." },

  // Ordering / general
  { category: "General", q: "How do I purchase an account?", a: "Tap the 'Buy Now' button on any account card — this opens WhatsApp with a pre-filled message including the account ID. Our team will respond with payment details and next steps." },
  { category: "General", q: "Can I request a custom account based on my preferences?", a: "Yes! Message us on WhatsApp with your budget, preferred rank, and the skins or evo guns you're looking for, and our team will source matching options or notify you when one becomes available." },
  { category: "General", q: "Do you operate 24/7?", a: "Our support team is active daily, with typical response times under 30 minutes during peak hours (10 AM – 11 PM) and slightly longer overnight." },
  { category: "General", q: "Are prices negotiable?", a: "Listed prices already reflect a fair market rate based on the account's rank and inventory. For bulk purchases or repeat customers, message us — we're happy to discuss." },
  { category: "General", q: "What regions do your accounts work in?", a: "Each listing notes its region binding (Global, SEA, etc.). Global accounts work worldwide, while region-locked accounts perform best within their listed server region." },
  { category: "General", q: "Do you provide warranty support after the sale?", a: "Yes — every purchase includes a 24-hour delivery warranty covering login access issues, plus ongoing support if you have questions about securing your new account." },
];
